import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { getDb, withTenantTx } from '../db/mongo.js';
import { Errors } from '../errors.js';
import { CLASSIFICATIONS, Classification } from '../authz/permissions.js';
import { config } from '../config.js';

/**
 * Registry for indexed source-code repositories (multi-repo code search).
 *
 * A repo is registered per tenant with exactly one source:
 * - `gitUrl`: cloned/updated by the indexer (private hosts authenticate with
 *   the GITHUB_TOKEN server secret — never stored on the repo row), or
 * - `localPath`: read directly from the backend host filesystem.
 *
 * Index state lives on the row (`status`, `commitSha`, `chunkCount`,
 * `lastSyncedAt`, `lastError`) so operators can see freshness per repo.
 * Chunks are namespaced by repoId, so identically-named files in different
 * repos never collide at retrieval time.
 *
 * MongoDB (ADR-014): `_id` is a UUID string generated by the application.
 * Tenant isolation is enforced by an explicit `tenantId` equality filter on
 * every query — there is no RLS. Deleting a repo explicitly deletes its
 * chunks and files first (no foreign-key cascades).
 */

export const REPO_STATUSES = ['PENDING', 'SYNCING', 'READY', 'FAILED'] as const;
export type RepoStatus = (typeof REPO_STATUSES)[number];

export interface RepoRecord {
  id: string;
  tenantId: string;
  name: string;
  gitUrl: string | null;
  localPath: string | null;
  defaultBranch: string;
  classification: Classification;
  status: RepoStatus;
  commitSha: string | null;
  chunkCount: number;
  lastSyncedAt: string | null;
  lastError: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Document shape for the `repos` collection. `_id` is an app-generated UUID string (ADR-014). */
interface RepoDoc {
  _id: string;
  tenantId: string;
  name: string;
  gitUrl: string | null;
  localPath: string | null;
  defaultBranch: string;
  classification: string;
  status: string;
  commitSha: string | null;
  chunkCount: number;
  lastSyncedAt: Date | null;
  lastError: string | null;
  createdAt: Date;
  updatedAt: Date;
}

/** Document shape for the `repo_files` collection. */
interface RepoFileDoc {
  _id: string;
  repoId: string;
  tenantId: string;
  path: string;
  content: string;
  classification: string;
  commitSha: string | null;
}

/** Document shape for the `repo_code_chunks` collection. */
interface RepoChunkDoc {
  _id: string;
  repoId: string;
  tenantId: string;
  path: string;
  chunkIndex: number;
  content: string;
  embedding: number[];
  classification: string;
  embeddingModel: string;
  embeddingVersion: string;
  embeddingDimensions: number;
  commitSha: string | null;
}

export const repoNameSchema = z
  .string()
  .trim()
  .min(1)
  .max(100)
  .regex(/^[A-Za-z0-9._-]+$/, 'Repo name may contain letters, digits, dot, underscore, and hyphen');

const gitUrlSchema = z
  .string()
  .trim()
  .min(1)
  .max(500)
  .regex(/^https?:\/\/[A-Za-z0-9.-]+(?::\d+)?\/\S+$/, 'gitUrl must be an http(s) URL');

const localPathSchema = z
  .string()
  .trim()
  .min(1)
  .max(500)
  .regex(/^\//, 'localPath must be an absolute path');

export const createRepoSchema = z
  .object({
    name: repoNameSchema,
    gitUrl: gitUrlSchema.optional(),
    localPath: localPathSchema.optional(),
    // Branch names are passed to `git clone --branch` / `fetch` / `reset`
    // via execFile (no shell), but a leading dash would still be parsed as
    // a git option — reject it, along with `..` and stray slashes.
    defaultBranch: z
      .string()
      .trim()
      .min(1)
      .max(100)
      .regex(/^[A-Za-z0-9._/-]+$/)
      .refine((branch) => !branch.startsWith('-') && !branch.startsWith('/') && !branch.endsWith('/') && !branch.includes('..'), {
        message: 'Invalid default branch name',
      })
      .default('main'),
    classification: z.enum(CLASSIFICATIONS).default('INTERNAL'),
  })
  .strict()
  .refine((value) => Boolean(value.gitUrl) !== Boolean(value.localPath), {
    message: 'Exactly one of gitUrl or localPath must be provided',
  });

export type CreateRepoInput = z.infer<typeof createRepoSchema>;

/**
 * Confinement for localPath registrations: the resolved path must be a
 * directory inside REPO_LOCAL_ROOT. Symlinks are resolved (realpath) so a
 * link pointing outside the root is rejected. Checked at registration and
 * again at every sync, so a path swapped after registration cannot escape.
 * Returns the resolved directory.
 */
export async function assertLocalPathAllowed(localPath: string): Promise<string> {
  const root = path.resolve(config.REPO_LOCAL_ROOT);
  let resolved: string;
  try {
    resolved = await fs.realpath(localPath);
  } catch {
    throw Errors.badRequest('REPO_LOCAL_PATH_INVALID', 'Configured localPath is not a readable directory');
  }
  const stat = await fs.stat(resolved).catch(() => null);
  if (!stat || !stat.isDirectory()) {
    throw Errors.badRequest('REPO_LOCAL_PATH_INVALID', 'Configured localPath is not a readable directory');
  }
  if (resolved !== root && !resolved.startsWith(root + path.sep)) {
    throw Errors.badRequest(
      'REPO_LOCAL_PATH_DENIED',
      `localPath must be inside REPO_LOCAL_ROOT (${root})`
    );
  }
  return resolved;
}

function toRepoRecord(doc: RepoDoc): RepoRecord {
  const toIso = (value: unknown): string | null =>
    value === null || value === undefined ? null : new Date(value as string | number | Date).toISOString();
  return {
    id: String(doc._id),
    tenantId: String(doc.tenantId),
    name: String(doc.name),
    gitUrl: (doc.gitUrl as string | null) ?? null,
    localPath: (doc.localPath as string | null) ?? null,
    defaultBranch: String(doc.defaultBranch),
    classification: doc.classification as Classification,
    status: doc.status as RepoStatus,
    commitSha: (doc.commitSha as string | null) ?? null,
    chunkCount: Number(doc.chunkCount ?? 0),
    lastSyncedAt: toIso(doc.lastSyncedAt),
    lastError: (doc.lastError as string | null) ?? null,
    createdAt: toIso(doc.createdAt) ?? new Date(0).toISOString(),
    updatedAt: toIso(doc.updatedAt) ?? new Date(0).toISOString(),
  };
}

export async function listRepos(tenantId: string): Promise<RepoRecord[]> {
  const db = await getDb();
  const docs = await db.collection<RepoDoc>('repos').find({ tenantId }).sort({ name: 1 }).toArray();
  return docs.map((doc) => toRepoRecord(doc));
}

export async function getRepo(tenantId: string, id: string): Promise<RepoRecord> {
  const db = await getDb();
  const doc = await db.collection<RepoDoc>('repos').findOne({ _id: id, tenantId });
  if (!doc) throw Errors.notFound('REPO_NOT_FOUND', 'Repository not found');
  return toRepoRecord(doc);
}

export async function getRepoByName(tenantId: string, name: string): Promise<RepoRecord> {
  const parsed = repoNameSchema.safeParse(name);
  if (!parsed.success) throw Errors.badRequest('INVALID_REPO_NAME', 'Invalid repository name');
  const db = await getDb();
  const doc = await db.collection<RepoDoc>('repos').findOne({ tenantId, name: parsed.data });
  if (!doc) throw Errors.notFound('REPO_NOT_FOUND', 'Repository not found');
  return toRepoRecord(doc);
}

export async function createRepo(tenantId: string, input: CreateRepoInput): Promise<RepoRecord> {
  // localPath registration is confined to REPO_LOCAL_ROOT: an admin API
  // credential must never become a read primitive for arbitrary server
  // paths (e.g. /etc), because indexed content is then readable through
  // repo.search/repo.readFile by any repo:read holder.
  if (input.localPath) {
    await assertLocalPathAllowed(input.localPath);
  }
  const now = new Date();
  const doc = {
    _id: randomUUID(),
    tenantId,
    name: input.name,
    gitUrl: input.gitUrl ?? null,
    localPath: input.localPath ?? null,
    defaultBranch: input.defaultBranch,
    classification: input.classification,
    status: 'PENDING' as RepoStatus,
    commitSha: null as string | null,
    chunkCount: 0,
    lastSyncedAt: null as Date | null,
    lastError: null as string | null,
    createdAt: now,
    updatedAt: now,
  };
  const db = await getDb();
  try {
    await db.collection<RepoDoc>('repos').insertOne(doc);
  } catch (error) {
    // Unique violation on (tenantId, name): report a clean 409, not a 500.
    if (error instanceof Error && 'code' in error && (error as { code?: number }).code === 11000) {
      throw Errors.conflict('REPO_ALREADY_EXISTS', 'A repository with this name is already registered');
    }
    throw error;
  }
  return toRepoRecord(doc);
}

export async function deleteRepo(tenantId: string, id: string): Promise<void> {
  // No foreign-key cascades in MongoDB: delete the repo's chunks and files
  // explicitly, in one transaction, so a repo is never left with orphaned
  // index rows (or an index without its repo row).
  await withTenantTx(tenantId, async (session, db) => {
    await db.collection<RepoChunkDoc>('repo_code_chunks').deleteMany({ tenantId, repoId: id }, { session });
    await db.collection<RepoFileDoc>('repo_files').deleteMany({ tenantId, repoId: id }, { session });
    const result = await db.collection<RepoDoc>('repos').deleteOne({ _id: id, tenantId }, { session });
    if (result.deletedCount === 0) throw Errors.notFound('REPO_NOT_FOUND', 'Repository not found');
  });
}

export async function setRepoSyncState(
  tenantId: string,
  id: string,
  state: { status: RepoStatus; commitSha?: string | null; chunkCount?: number; lastError?: string | null }
): Promise<void> {
  const db = await getDb();
  const update: Record<string, unknown> = {
    status: state.status,
    lastError: state.lastError ?? null,
    updatedAt: new Date(),
  };
  if (state.commitSha !== undefined && state.commitSha !== null) update.commitSha = state.commitSha;
  if (state.chunkCount !== undefined) update.chunkCount = state.chunkCount;
  if (state.status === 'READY') update.lastSyncedAt = new Date();
  await db.collection<RepoDoc>('repos').updateOne({ _id: id, tenantId }, { $set: update });
}

/**
 * Atomically replace a repo's index set after a successful sync: the exact
 * file rows and the chunk rows are swapped in one transaction, so a failed
 * sync never leaves the repo with a half-built or empty index. The file
 * rows hold the exact indexed content, so repo.readFile never re-stitches
 * overlapping chunks.
 */
export async function replaceRepoIndex(
  tenantId: string,
  repoId: string,
  classification: Classification,
  files: Array<{ path: string; content: string; commitSha: string | null }>,
  chunks: Array<{ path: string; chunkIndex: number; content: string; embedding: number[]; commitSha: string | null }>,
  embeddingModel: string,
  embeddingVersion: string,
  embeddingDimensions: number
): Promise<void> {
  await withTenantTx(tenantId, async (session, db) => {
    await db.collection<RepoChunkDoc>('repo_code_chunks').deleteMany({ tenantId, repoId }, { session });
    await db.collection<RepoFileDoc>('repo_files').deleteMany({ tenantId, repoId }, { session });

    if (files.length > 0) {
      await db.collection<RepoFileDoc>('repo_files').insertMany(
        files.map((file) => ({
          _id: randomUUID(),
          repoId,
          tenantId,
          path: file.path,
          content: file.content,
          classification,
          commitSha: file.commitSha,
        })),
        { session }
      );
    }

    if (chunks.length > 0) {
      await db.collection<RepoChunkDoc>('repo_code_chunks').insertMany(
        chunks.map((chunk) => ({
          _id: randomUUID(),
          repoId,
          tenantId,
          path: chunk.path,
          chunkIndex: chunk.chunkIndex,
          content: chunk.content,
          // Stored as a plain number array (1536 dims); the Atlas Vector
          // Search index `idx_repo_code_chunks_embedding_vector` is built
          // over this field (see migration 005).
          embedding: chunk.embedding,
          classification,
          embeddingModel,
          embeddingVersion,
          embeddingDimensions,
          commitSha: chunk.commitSha,
        })),
        { session }
      );
    }
  });
}
