/**
 * 001_init — core identity collections (ADR-014).
 *
 * Ports SQL migrations 001_init, 009_session_security, 010_login_lockout,
 * 012_refresh_token_history (DDL only) plus the seed/grant data from
 * 002_seed, 004, 006, 011, 019, 022, 026, 027.
 *
 * Field naming is camelCase to match the TypeScript data layer. `_id` is a
 * UUID string (crypto.randomUUID()), generated by the application — the
 * MongoDB equivalent of Postgres `gen_random_uuid()` defaults.
 *
 * Not ported (no MongoDB equivalent, handled elsewhere):
 *  - RLS policies / FORCE RLS — defense in depth only; every application
 *    query filters `tenantId` explicitly (see db-inventory §5a).
 *  - Foreign keys — referential integrity is enforced in application code.
 */

import { randomUUID } from 'crypto';
import type { Db } from 'mongodb';
import type { Migration } from '../migrate.js';
import { coll, insertManyIdempotent } from './helpers.js';

const ROLES = [
  'User',
  'Admin',
  'Security Admin',
  'AI Admin',
  'Developer',
  'Read Only',
] as const;

/**
 * Final permission set after the complete SQL history:
 * 002_seed minus `tool:admin`/`user:manage` (removed by 011), plus
 * `document:classify` (004), `conversation:update` (006), `syteline:read`
 * (019), `retention:manage` (022), `repo:read`/`repo:manage` (026),
 * `memory:read`/`memory:write` (027).
 */
const PERMISSIONS = [
  'chat:create',
  'conversation:read',
  'conversation:delete',
  'conversation:update',
  'document:upload',
  'document:read',
  'document:delete',
  'document:classify',
  'model:use',
  'model:manage',
  'tool:use',
  'audit:read',
  'tenant:manage',
  'syteline:read',
  'retention:manage',
  'repo:read',
  'repo:manage',
  'memory:read',
  'memory:write',
] as const;

/**
 * Role → permission grants, combining the 002_seed grants with the later
 * per-permission grants (004, 006, 019, 022, 026, 027) and dropping the
 * 011-removed `tool:admin` / `user:manage`.
 */
const ROLE_GRANTS: Record<string, readonly string[]> = {
  User: [
    'chat:create',
    'conversation:read',
    'conversation:delete',
    'conversation:update', // 006
    'document:upload',
    'document:read',
    'model:use',
    'tool:use',
    'syteline:read', // 019
    'repo:read', // 026
    'memory:read', // 027
    'memory:write', // 027
  ],
  // Admin holds every permission (002 seeded "all permissions").
  Admin: PERMISSIONS,
  'Security Admin': [
    'audit:read',
    // 'user:manage' removed by 011
    'tenant:manage',
    'conversation:read',
    'document:read',
    'document:classify', // 004
    'retention:manage', // 022
  ],
  'AI Admin': [
    'model:manage',
    'model:use',
    // 'tool:admin' removed by 011
    'tool:use',
    'chat:create',
    'conversation:read',
    'document:read',
    'syteline:read', // 019
    'repo:read', // 026
    'repo:manage', // 026
    'memory:read', // 027
    'memory:write', // 027
  ],
  Developer: [
    'chat:create',
    'conversation:read',
    'conversation:update', // 006
    'document:upload',
    'document:read',
    'model:use',
    'tool:use',
    'syteline:read', // 019
    'repo:read', // 026
    'memory:read', // 027
    'memory:write', // 027
  ],
  'Read Only': [
    'conversation:read',
    'document:read',
    'memory:read', // 027
  ],
};

export const migration001: Migration = {
  version: '001_init',
  description:
    'Core identity collections (organizations, tenants, users, roles, permissions, role_permissions, memberships, sessions) with indexes and seed data',

  up: async (db: Db): Promise<void> => {
    // ------------------------------------------------------------------
    // Indexes (createIndex is idempotent when name + spec match)
    // ------------------------------------------------------------------
    await db
      .collection('tenants')
      .createIndex({ organizationId: 1 }, { name: 'idx_tenants_org' });

    // 014 dropped the redundant PG index because UNIQUE(email) carries its
    // own btree; MongoDB unique constraints carry no index, so the unique
    // index on email is required here.
    await db
      .collection('users')
      .createIndex({ email: 1 }, { unique: true, name: 'idx_users_email' });

    await db
      .collection('roles')
      .createIndex({ name: 1 }, { unique: true, name: 'idx_roles_name' });

    await db
      .collection('permissions')
      .createIndex({ name: 1 }, { unique: true, name: 'idx_permissions_name' });

    await db
      .collection('role_permissions')
      .createIndex(
        { roleId: 1, permissionId: 1 },
        { unique: true, name: 'idx_role_permissions_pk' }
      );

    await db
      .collection('memberships')
      .createIndex(
        { userId: 1, tenantId: 1 },
        { unique: true, name: 'idx_memberships_user_tenant' }
      );
    await db
      .collection('memberships')
      .createIndex({ userId: 1 }, { name: 'idx_memberships_user' });
    await db
      .collection('memberships')
      .createIndex({ tenantId: 1 }, { name: 'idx_memberships_tenant' });
    // NOTE: RLS was deliberately NOT enabled on memberships (008): login
    // resolves memberships by userId before any tenant context exists.

    await db
      .collection('sessions')
      .createIndex(
        { refreshTokenHash: 1 },
        { unique: true, name: 'idx_sessions_refresh_token_hash' }
      );
    // Active-session lookup: replaces the PG partial index
    // `... WHERE revoked_at IS NULL`. In MongoDB, `revokedAt: null` in the
    // partialFilterExpression matches documents where the field is null OR
    // absent.
    await db.collection('sessions').createIndex(
      { userId: 1, tenantId: 1, expiresAt: 1 },
      {
        name: 'idx_sessions_active',
        partialFilterExpression: { revokedAt: null },
      }
    );
    // Reuse-detection hot path (009): superseded token hashes.
    await db.collection('sessions').createIndex(
      { replacedRefreshTokenHash: 1 },
      {
        name: 'idx_sessions_replaced_hash',
        partialFilterExpression: {
          replacedRefreshTokenHash: { $exists: true, $ne: null },
        },
      }
    );
    // Rolling refresh-token history (012): multikey index replaces the PG
    // GIN index; `{ previousRefreshTokenHashes: hash }` matches by element.
    await db
      .collection('sessions')
      .createIndex(
        { previousRefreshTokenHashes: 1 },
        { name: 'idx_sessions_prev_hashes' }
      );

    // ------------------------------------------------------------------
    // Seed data (idempotent via unique indexes + ordered:false inserts)
    // ------------------------------------------------------------------
    const now = new Date();

    await insertManyIdempotent(
      coll(db, 'roles'),
      ROLES.map((name) => ({ _id: randomUUID(), name, createdAt: now }))
    );

    await insertManyIdempotent(
      coll(db, 'permissions'),
      PERMISSIONS.map((name) => ({ _id: randomUUID(), name, createdAt: now }))
    );

    // Resolve ids by name so grants survive re-runs with fresh UUIDs.
    const roleDocs = await coll(db, 'roles')
      .find({ name: { $in: [...ROLES] } })
      .project({ _id: 1, name: 1 })
      .toArray();
    const permDocs = await coll(db, 'permissions')
      .find({ name: { $in: [...PERMISSIONS] } })
      .project({ _id: 1, name: 1 })
      .toArray();
    const roleIdByName = new Map(roleDocs.map((r) => [r.name, r._id]));
    const permIdByName = new Map(permDocs.map((p) => [p.name, p._id]));

    const grants: Array<{ _id: string; roleId: string; permissionId: string }> = [];
    for (const [roleName, permNames] of Object.entries(ROLE_GRANTS)) {
      const roleId = roleIdByName.get(roleName);
      if (!roleId) continue;
      for (const permName of permNames) {
        const permissionId = permIdByName.get(permName);
        if (!permissionId) continue;
        grants.push({ _id: randomUUID(), roleId, permissionId });
      }
    }
    await insertManyIdempotent(coll(db, 'role_permissions'), grants);
  },
};
