/**
 * deck.ts — implementation-plan deck config + build.
 *
 * Generates `plan/deck.config.js` (all project content lives there; the
 * shared `plan/build_impl_deck.js` build script renders it) and runs the
 * build to produce the PPTX. Brand style: white slides, red rounded icon
 * badge, Segoe UI Light title, Calibri body, square bullets, red outlined
 * milestone circles, thin red decorative arcs, Enflite logo.
 *
 * The build needs the project's `plan/package.json` deps (`pptxgenjs`).
 * That is installed by `buildDeck` with `npm install` unless `skipInstall`
 * is set (use when the deps are already present, e.g. in tests).
 */

import { writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

export interface DeckPhase {
  heading: string;
  bullets: string[];
}

export interface DeckInput {
  formName: string;
  title: string;
  subtitle: string;
  fileName: string;
  brd: string[][];
  scope: { sub: string; flow: string[] };
  /** One string per row, e.g. `Test | Uf_ENF_Test | UET user field | Text | Added by this project`. */
  design: string[];
  develop: string[];
  formsync: string[];
  staging: string[];
  launch: string[];
  test: string[];
  optimize: string[];
  rollback: string[];
  /** `[heading, bullets]` tuples for the phase summary slide. */
  phases: Array<[string, string[]]>;
  mockupImage?: string;
}

function jsStringArray(rows: string[][] | string[]): string {
  const line = (s: string) => JSON.stringify(s);
  if (rows.length > 0 && Array.isArray(rows[0])) {
    return (rows as string[][]).map((r) => `    [${r.map(line).join(', ')}],`).join('\n');
  }
  return (rows as string[]).map((s) => `    ${line(s)},`).join('\n');
}

export function renderDeckConfig(input: DeckInput): string {
  const phases = input.phases
    .map(([h, b]) => `    [${JSON.stringify(h)}, [\n${b.map((x) => `      ${JSON.stringify(x)},`).join('\n')}\n    ]],`)
    .join('\n');
  return `// Auto-generated by the backend-ai syteline form-build module. Do not edit by hand;
// regenerate from the project inputs instead.
module.exports = {
  title: ${JSON.stringify(`${input.formName} — ${input.title}`)},
  subtitle: ${JSON.stringify(input.subtitle)},
  fileName: ${JSON.stringify(input.fileName)},
  brd: [
${jsStringArray(input.brd)}
  ],
  scope: {
    sub: ${JSON.stringify(input.scope.sub)},
    flow: [
${jsStringArray(input.scope.flow)}
    ],
  },
  design: [
${jsStringArray(input.design)}
  ],
  develop: [
${jsStringArray(input.develop)}
  ],
  formsync: [
${jsStringArray(input.formsync)}
  ],
  staging: [
${jsStringArray(input.staging)}
  ],
  launch: [
${jsStringArray(input.launch)}
  ],
  test: [
${jsStringArray(input.test)}
  ],
  optimize: [
${jsStringArray(input.optimize)}
  ],
  rollback: [
${jsStringArray(input.rollback)}
  ],
  phases: [
${phases}
  ],
${input.mockupImage ? `  mockup: { image: ${JSON.stringify(input.mockupImage)} },` : ''}
};
`;
}

export interface BuildDeckOptions {
  /** The form project's root (contains `plan/`). */
  projectDir: string;
  /** Skip `npm install` (deps already present). */
  skipInstall?: boolean;
  /** Timeout per npm step in ms. */
  timeoutMs?: number;
}

/** Write `plan/deck.config.js` and build the PPTX via `npm run build`. */
export function buildDeck(input: DeckInput, options: BuildDeckOptions): string {
  const planDir = join(options.projectDir, 'plan');
  writeFileSync(join(planDir, 'deck.config.js'), renderDeckConfig(input), 'utf8');
  const timeout = options.timeoutMs ?? 120_000;
  if (!options.skipInstall) {
    execFileSync('npm', ['install'], { cwd: planDir, timeout, stdio: 'pipe' });
  }
  execFileSync('npm', ['run', 'build'], { cwd: planDir, timeout, stdio: 'pipe' });
  return join(planDir, input.fileName);
}
